In [1]:
import numpy as np
import pandas as pd

In [2]:
dt = pd.read_csv("Fish.csv")

In [3]:
dt.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [4]:
dt.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [5]:
x = dt.iloc[:,[0,2,3,4,5,6]].values
y = dt.iloc[:,1].values

In [6]:
x.shape

(159, 6)

In [7]:
y.shape

(159,)

In [8]:
dt.Species.unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
c =ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder="passthrough")
x=c.fit_transform(x)

In [10]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2,random_state = 1)

In [11]:
xtrain

array([[0.0, 0.0, 1.0, ..., 37.3, 11.4884, 7.7957],
       [0.0, 0.0, 0.0, ..., 39.8, 6.2884, 4.0198],
       [0.0, 0.0, 0.0, ..., 34.0, 10.744000000000002, 6.562],
       ...,
       [0.0, 0.0, 1.0, ..., 8.8, 2.112, 1.4080000000000001],
       [0.0, 0.0, 0.0, ..., 55.1, 8.9262, 6.1712],
       [0.0, 0.0, 0.0, ..., 21.2, 5.5756, 2.9044]], dtype=object)

In [12]:
ytrain

array([ 840. ,  300. ,  540. ,  300. ,  160. ,  200. ,  975. ,  270. ,
        430. ,  556. ,  250. ,   12.2,  500. ,  700. ,   51.5,  850. ,
        272. ,  650. ,  540. ,  700. ,  100. ,   19.7,  340. ,   78. ,
        610. ,  169. ,  150. ,  430. ,  160. , 1250. ,  120. ,   69. ,
       1000. ,    7. ,   10. ,    7.5,  820. ,  340. , 1100. ,  685. ,
        500. ,  242. ,  850. ,  150. ,  270. ,  130. ,  130. ,  140. ,
         60. ,   40. , 1100. ,  180. ,  300. ,  170. ,  475. ,  950. ,
        925. ,  300. ,   87. ,  115. ,  900. ,   19.9,  714. ,  680. ,
        170. ,  500. ,  510. ,  265. ,  900. ,  567. ,  120. ,  188. ,
          9.7,  820. ,  120. ,  600. ,  110. ,  110. ,  514. ,   85. ,
        290. ,  720. ,   70. ,  150. ,  700. ,  700. ,    9.9, 1000. ,
          9.8,  161. ,  685. ,  273. ,  363. ,    8.7,  920. ,   12.2,
       1015. ,  690. ,  450. , 1000. ,  200. ,  290. ,  306. ,  620. ,
         55. ,   90. ,  390. ,   13.4,  120. ,  225. ,  145. ,  200. ,
      

In [13]:
from sklearn.linear_model import LinearRegression
m = LinearRegression()
m.fit(xtrain,ytrain)
ypred = m.predict(xtest)

In [14]:
ytest

array([1000. ,  120. ,  600. ,  130. ,   85. ,  650. ,  145. ,  500. ,
          0. ,  145. ,  135. ,  150. ,   32. ,  250. ,  800. ,  110. ,
        140. ,  390. ,  320. ,  197. ,    9.8,   40. ,  180. ,  450. ,
        125. ,  955. ,  700. ,    6.7, 1550. ,  145. , 1000. ,  260. ])

In [15]:
ypred

array([ 7.86895932e+02,  1.06877114e+02,  5.46186655e+02,  1.93616759e+02,
        7.06776027e+01,  6.04768801e+02,  1.22903964e+02,  4.87351516e+02,
        7.07685529e+01,  2.42687360e+02,  1.74814756e+02,  2.15594484e+02,
       -1.85242525e+02,  3.71342788e+02,  7.11881818e+02,  1.88966132e+02,
        1.83488387e+02,  5.36004961e+02,  4.67590714e+02,  3.08048929e+02,
       -6.21706849e-01, -1.71049562e+02,  2.49667531e+02,  4.95212598e+02,
        1.47155398e+02,  8.33637984e+02,  5.84900687e+02, -8.34558034e+01,
        1.28046673e+03,  1.99423873e+02,  1.02700516e+03,  3.66930286e+02])

In [16]:
from sklearn.metrics import r2_score
a = r2_score(ypred,ytest)
a

0.8892618037290665

In [17]:
m.predict(c.transform([["Roach",23.5,25.5,30.5,10.5,4.02]]))

array([321.92116844])